project_name: fail2ban_exporter
builds:
  - env: [CGO_ENABLED=0]
    binary: fail2ban_exporter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

dockers:
- image_templates:
  - "registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}-amd64"
  - "registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}.{{ .Minor }}-amd64"
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Version }}-amd64'
  - "registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest-amd64"
  extra_files:
  - health
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
  - --label=org.opencontainers.image.source=https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates:
  - "registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}-arm64"
  - "registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}.{{ .Minor }}-arm64"
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Version }}-arm64'
  - "registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest-arm64"
  extra_files:
  - health
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/arm64"
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
  - --label=org.opencontainers.image.source=https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  goarch: arm64

docker_manifests:
- name_template: 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}-amd64'
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}-arm64'

- name_template: 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}.{{ .Minor }}'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}.{{ .Minor }}-amd64'
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Major }}.{{ .Minor }}-arm64'

- name_template: 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Version }}'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Version }}-amd64'
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:{{ .Version }}-arm64'

- name_template: 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest-amd64'
  - 'registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest-arm64'

nfpms:
- id: prometheus-fail2ban-exporter
  
  package_name: prometheus-fail2ban-exporter
  
  vendor: hectorjsmith
  
  homepage: https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
  
  maintainer: hectorjsmith <[email protected]>
  
  description: |-
    Collect metrics from a running fail2ban instance.
  
  license: MIT License
  
  formats:
#    - apk
    - deb

  section: net

  dependencies:
    - adduser

  contents:
    - src: "{{ .ArtifactPath }}"
      dst: /usr/bin/prometheus-fail2ban-exporter
    - src: README.md
      dst: /usr/share/doc/prometheus-fail2ban-exporter/README.md
    - src: LICENSE
      dst: /usr/share/doc/prometheus-fail2ban-exporter/copyright
    - src: _system/default
      dst: /etc/default/prometheus-fail2ban-exporter
    - src: _system/systemd/prometheus-fail2ban-exporter.service
      dst: /lib/systemd/system/prometheus-fail2ban-exporter.service

  scripts:
    postinstall: "_system/postinst"
    preremove: "_system/prerm"
    postremove: "_system/postrm"

changelog:
  groups:
    - title: "⛔ Breaking Changes"
      regexp: '^.*?!:.+$'
      order: 0
    - title: "🎉 Features"
      regexp: '^.*?feat(\(\w+\))??:.+$'
      order: 1
    - title: "🐛 Fixes"
      regexp: '^.*?fix(\(\w+\))??:.+$'
      order: 2
    - title: "📑 Other"
      order: 999
  filters:
    exclude:
      - "^Merge"
      - "^merge"
